### GetAllCurrenciesRequest
### http200 - Успех
GET http://localhost:8080/currencies
Accept: application/json

### GetCurrencyByIdRequest
### http200 - Успех
GET http://localhost:8080/currency/USD
Accept: application/json

### GetCurrencyByIdRequest
### http400Errors - Код валюты отсутствует в адресе
GET http://localhost:8080/currency/
Accept: application/json

### GetCurrencyByIdRequest
### http404Errors - Валюта не найдена
GET http://localhost:8080/currency/what
Accept: application/json

### PostCurrenciesrRequest
### http201 - Успех
POST http://localhost:8080/currencies
Accept: application/json
Content-Type: application/x-www-form-urlencoded

name=Euro&code=EUR&sign=€

### PostCurrenciesrRequest
### http400Errors - Отсутствует нужное поле формы
POST http://localhost:8080/currencies
Accept: application/json
Content-Type: application/x-www-form-urlencoded

name=Euro&code=&sign=€

### PostCurrenciesrRequest
### http409Errors - Валюта с таким кодом уже существует | Доблировал код http201, чтобы показать явно
POST http://localhost:8080/currencies
Accept: application/json
Content-Type: application/x-www-form-urlencoded

name=Euro&code=EUR&sign=€
