### GetAllCurrenciesRequest
GET http://localhost:8080/currencies
Accept: application/json

### GetAllExchangeRatesRequest
GET http://localhost:8080/exchangeRates
Accept: application/json

### GetCurrencyByIdRequest
GET http://localhost:8080/currency/USD
Accept: application/json

### GetExchangeCalculationRequest
GET http://localhost:8080/exchange?from=JPY&to=EUR&amount=100
Accept: application/json

### GetExchangeRateCalculationRequest
GET http://localhost:8080/exchange?from=JPY&to=EUR&amount=100
Accept: application/json

### GetExchangeRatesByCurrencyPairRequest
GET http://localhost:8080/exchangeRate/USDEUR
Accept: application/json

### PatchExchangeRatesRequest
PATCH http://localhost:8080/exchangeRate/GBPAUD
Content-Type: application/x-www-form-urlencoded

rate=0.32

### PostCurrenciesrRequest
POST http://localhost:8080/currencies
Accept: application/json
Content-Type: application/x-www-form-urlencoded

name=Euro&code=EUR&sign=€

### PostExchangeRatesRequest
POST http://localhost:8080/exchangeRates
Accept: application/json
Content-Type: application/x-www-form-urlencoded

baseCurrencyCode=EUR&targetCurrencyCode=EUR&rate=0.32
